blank_issues_enabled: false
contact_links:
  - name: Get support from the community
    url: https://github.com/solarpointwp/framework/discussions/categories/q-a
    about: Browse existing discussions or ask the community for help
